### PR TITLE
Add results page

### LINKED ISSUE #174: Results page
Hello!
We have submitted our first paper and now need a results page at www.planetfour.org/results
similar to https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/results.
Because I want to put the paper on arXiv, if possible, I'd like this to go live soon, so that the paper is available for proposal reviewers, pretty please? ;)
Thanks in advance!

### PR DESCRIPTION
**Pull request by adammcmaster**
Closes #174

### CODE REVIEW

**Comment by adammcmaster** [comment]
This is staged at https://www.planetfour.org/beta/#/results

@mschwamb @michaelaye Could you let me know if you want any additional text on this page? It looks a bit plain at the moment.

**Comment by mschwamb** [comment]
For the top can you add this:

> This page allows anyone to download the data files associated with Planet Four papers. Planet Four  is described in [Aye et al. (in press)](http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1803.10341). Anyone making use of Planet Four data should cite this paper in any resulting publications as well as the appropriate data release paper.

Maybe had a hr to separate from the rest of the page and then

> Data Release 1

> Planet Four: Probing Springtime Winds on Mars by Mapping the Southern Polar CO2 Jet Deposits

> K.-Michael Aye,  Megan E. Schwamb, Ganna Portyankina, Candice J. Hansen, Adam McMaster, Grant R.M. Miller, Brian Carstensen, Christopher Snyder, Michael Parrish, Stuart Lynn, Chuhong Mai, David Miller, Robert J. Simpson, &  Arfon M. Smith, Planet Four: Probing Springtime Winds on Mars by Mapping the Southern Polar CO2 Jet Deposits, Icarus,in press ([pre-print version](https://arxiv.org/abs/1803.10341))

> Abstract: 
> The springtime sublimation process of Mars’ southern seasonal polar CO2 ice cap features dark fan-shaped deposits appearing on the top of the thawing ice sheet. The fan material likely originates from the surface below the ice sheet, brought up via CO2 jets breaking through the seasonal ice cap. Once the dust and dirt is released into the atmosphere, the material may be blown by the surface winds into the dark streaks visible from orbit. The location, size and direction of these fans record a number of parameters important to quantifying seasonal winds and sublimation activity, the most important agent of geological change extant on Mars. We present results of a systematic mapping of these south polar seasonal fans with the Planet Four online citizen science project. Planet Four enlists the general public to map the shapes, directions, and sizes of the seasonal fans visible in orbital images. Over 80,000 volunteers have contributed to the Planet Four project, reviewing 221 images, from Mars Reconnaissance Orbiter’s HiRISE (High Resolution Imaging Science Experiment) camera, taken in southern spring during Mars Years 29 and 30. We provide an overview of Planet Four and detail the processes of combining multiple volunteer assessments together to generate a high fidelity catalog of ∼400,000 south polar seasonal fans. We present the results from analyzing the wind directions at several locations monitored by HiRISE over two Mars years, providing new insights into polar surface winds.

After all the stuff currently on the page, can you add:

> We acknowledge the contributions of the Planet Four volunteer community to this work here. 

Adding a link to the authors page 

Thanks @adammcmaster

**Comment by adammcmaster** [comment]
I've updated https://www.planetfour.org/beta/#/results with that content. Let me know if that all looks OK.

**Comment by mschwamb** [comment]
Looks good to me

**Comment by michaelaye** [comment]
looks good, yes!

**Comment by mschwamb** [comment]
Can you also make a redirect for https://www.planetfour.org/results to https://www.planetfour.org/beta/#/results - this way we've got it from when we switch to panoptes and these pages potentially move. Thanks @adammcmaster

**Comment by adammcmaster** [comment]
That's all live now.

**Pull request merged**
